export const CHANGE_SINGER_LIST = 'singers/CHANGE_SINGER_LIST'
export const CHANGE_PAGE_COUNT = 'singers/PAGE_COUNT'
export const CHANGE_ENTER_LOADING = 'singers/ENTER_LOADING'
export const CHANGE_PULL_UP_LOADING = 'singers/PULL_UP_LOADING'
export const CHANGE_PULL_DOWN_LOADING = 'singers/PULL_DOWN_LOADING'